### ISSUE TITLE
enable non strict-ssl download option

### ISSUE THREAD

**Issue by p2227** [kevva/download#99] opened 2016-05-12 09:01 UTC
this issues is about:
https://github.com/imagemin/optipng-bin/issues/74

I find out how to solve it.but it need to read a conf from `.npmrc` .could I send a PR  ?

**Comment by shinnn** [comment] 2016-05-12 09:04
Almost duplicate of https://github.com/kevva/download/issues/97

**Closed by shinnn** 2016-05-12 09:04 UTC
